version: "3"
services:
  postgres:
    image: postgres:9.6.12
    ports:
     - "5433:5432"
    volumes:
     - "$HOME/docker/volumes/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 123
